# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        self.logoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout.addWidget(self.logoLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.shortcutInfo = QtWidgets.QLabel(parent=self.centralwidget)
        self.shortcutInfo.setObjectName("shortcutInfo")
        self.verticalLayout.addWidget(self.shortcutInfo)
        self.statusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.recordButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.recordButton.setObjectName("recordButton")
        self.verticalLayout.addWidget(self.recordButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        self.playButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.playButton.setObjectName("playButton")
        self.verticalLayout.addWidget(self.playButton)
        self.stopPlayingButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopPlayingButton.setObjectName("stopPlayingButton")
        self.verticalLayout.addWidget(self.stopPlayingButton)
        self.repeatInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.repeatInput.setObjectName("repeatInput")
        self.verticalLayout.addWidget(self.repeatInput)
        self.delayInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.delayInput.setObjectName("delayInput")
        self.verticalLayout.addWidget(self.delayInput)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mouse and Keyboard Recorder"))
        self.titleLabel.setText(_translate("MainWindow", "Mouse and Keyboard Recorder"))
        self.titleLabel.setStyleSheet(_translate("MainWindow", "font-size: 20px; font-weight: bold;"))
        self.shortcutInfo.setText(_translate("MainWindow", "Shortcut Keys:"))
        self.statusLabel.setText(_translate("MainWindow", "Status: Idle"))
        self.recordButton.setText(_translate("MainWindow", "Start Recording"))
        self.stopButton.setText(_translate("MainWindow", "Stop Recording"))
        self.playButton.setText(_translate("MainWindow", "Play Recording"))
        self.stopPlayingButton.setText(_translate("MainWindow", "Stop Playing"))
        self.repeatInput.setPlaceholderText(_translate("MainWindow", "Repeat count (default 1)"))
        self.delayInput.setPlaceholderText(_translate("MainWindow", "Delay after playback (seconds)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
